name: End-to-End Tests

# Allow running this workflow manually from the GitHub UI
# (This only works with the default branch, so that's why mjzffr/gutenberg has # 'firefox-ci' set as the default branch instead of 'master')
on: workflow_dispatch

jobs:
  admin:
    name: Admin - ${{ matrix.part }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        part: [1, 2, 3, 4]


    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Npm install and build
      run: |
        npm ci
        FORCE_REDUCED_MOTION=true npm run build

    - name: Install WordPress
      run: |
        chmod -R 767 ./ # TODO: Possibly integrate in wp-env
        npm run wp-env start

    - name: Use Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Guteberg depends on Puppeteer 3 so we need to install Nightly ourselves
    - name: Install Firefox Nightly
      env:
        FIREFOX_PATH: $GITHUB_WORKSPACE/firefox-latest
      run: |
        python -m pip install --upgrade pip
        pip install mozdownload
        rm -rf $FIREFOX_PATH
        mozdownload -t daily -d $FIREFOX_PATH/latest.tar.bz --log-level DEBUG
        cd $FIREFOX_PATH; tar -xvf latest.tar.bz; cd -
        ls $FIREFOX_PATH/firefox/firefox

    - name: Running the tests (Firefox)
      env:
        PUPPETEER_SKIP_DOWNLOAD: 1
        PUPPETEER_TIMEOUT: 25
        PUPPETEER_EXECUTABLE_PATH: $GITHUB_WORKSPACE/firefox-latest/firefox/firefox
        JEST_PUPPETEER_CONFIG: ./packages/scripts/config/puppeteer-firefox.config.js
      run: |
        ls $PUPPETEER_EXECUTABLE_PATH
        $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --listTests | grep test\.js$ > ~/.jest-e2e-tests
        $( npm bin )/wp-scripts test-e2e --config=./packages/e2e-tests/jest.config.js --cacheDirectory="$HOME/.jest-cache" --runTestsByPath $( awk 'NR % 4 == ${{ matrix.part }} - 1' < ~/.jest-e2e-tests )

    - name: Archive debug artifacts (screenshots, HTML snapshots)
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: failures-artifacts
        path: artifacts
